name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  gpio_driver:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: unittest
    steps:
    - uses: actions/checkout@v2
      with:
          repository: smuuze/rpi_control_frmwrk
          path: ../rpi_control_frmwrk
    - name: unittest
      run: |
        ls
        ls ..
