name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  unittest:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: unittest
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run: bash make_unittest.sh
