name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  gpio_driver:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: unittest/gpio_driver_rp2040
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run: make clean all run
      
  irq_driver:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: unittest/irq_interface_rp2040
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run: make clean all run
      
  uart_driver:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: unittest/uart_driver_rp2040
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run: make clean all run
